// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "SetpointCommand1.h"
double SetpointCommand1::points[]={.1,.2,.3,.4,.5,.6,.7,.8,.9};
int SetpointCommand1::counter=3;
bool SetpointCommand1::first =false;
bool SetpointCommand1::joystick=false;
SetpointCommand1::SetpointCommand1() {

	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pIDSubsystem1);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void SetpointCommand1::Initialize() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
	Robot::pIDSubsystem1->Enable();
	//Robot::pIDSubsystem1->SetSetpoint(0.5);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
}

// Called repeatedly when this Command is scheduled to run
void SetpointCommand1::Execute() {
	if(Robot::oi->getJoystick1()->GetY()>.05||Robot::oi->getJoystick1()->GetY()<-.05){
	joystick=true;
}
else{
Robot::pIDSubsystem1->Disable();
}
	if(joystick){
		Robot::pIDSubsystem1->Disable();
	}else{
		Robot::pIDSubsystem1->Enable();
	}
	printf("%.2f\n",Robot::pIDSubsystem1->GetSetpoint());
	if(Robot::pIDSubsystem1->limitSwitch1->Get()&&Robot::pIDSubsystem1->limitSwitch2->Get()){
		if(Robot::oi->getJoystick1()->GetRawButton(6)){
			if(first){
				Robot::pIDSubsystem1->SetSetpointRelative(1.0);
				joystick=false;
				first=false;
			}
		}else if(Robot::oi->getJoystick1()->GetRawButton(7)){
			if(first){
				Robot::pIDSubsystem1->SetSetpointRelative(-1.0);
				joystick=false;
				first=false;
			}
		}else{
			first=true;
		}

}

// Make this return true when this Command no longer needs to run execute()
bool SetpointCommand1::IsFinished() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
	return Robot::pIDSubsystem1->OnTarget();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
}

// Called once after isFinished returns true
void SetpointCommand1::End() {
	//Robot::pIDSubsystem1->Disable();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetpointCommand1::Interrupted() {

}
