// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
AnalogPotentiometer* RobotMap::pIDSubsystem1AnalogPotentiometer1 = NULL;
DigitalInput* RobotMap::pIDSubsystem1LimitSwitch1 = NULL;
DigitalInput* RobotMap::pIDSubsystem1LimitSwitch2 = NULL;
SpeedController* RobotMap::pIDSubsystem1SpeedController1 = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	pIDSubsystem1AnalogPotentiometer1 = new AnalogPotentiometer(0, 50.0, 0.0);
	lw->AddSensor("PID Subsystem 1", "Analog Potentiometer 1", pIDSubsystem1AnalogPotentiometer1);
	
	pIDSubsystem1LimitSwitch1 = new DigitalInput(0);
	lw->AddSensor("PID Subsystem 1", "Limit Switch 1", pIDSubsystem1LimitSwitch1);
	
	pIDSubsystem1LimitSwitch2 = new DigitalInput(1);
	lw->AddSensor("PID Subsystem 1", "Limit Switch 2", pIDSubsystem1LimitSwitch2);
	
	pIDSubsystem1SpeedController1 = new Talon(0);
	lw->AddActuator("PID Subsystem 1", "Speed Controller 1", (Talon*) pIDSubsystem1SpeedController1);
	


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
